export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCESS= "CREATE_ORDER_SUCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const  MY_ORDER_REQUEST = "MY_ORDER_REQUEST";
export const  MY_ORDER_SUCESS = "MY_ORDER_SUCESS";
export const  MY_ORDER_FAIL = "MY_ORDER_FAIL";

export const ALL_ORDER_REQUEST = "ALL_ORDER_REQUEST";
export const ALL_ORDER_SUCESS = "ALL_ORDER_SUCESS";
export const ALL_ORDER_FAIL = "ALL_ORDER_FAIL";

export const UPDATE_ORDER_REQUEST ="UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_SUCESS ="UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_RESET ="UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_FAIL ="UPDATE_ORDER_REQUEST"; 

export const DELETE_ORDER_REQUEST ="DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCESS ="DELETE_ORDER_REQUEST";
export const DELETE_ORDER_RESET ="DELETE_ORDER_REQUEST";
export const DELETE_ORDER_FAIL ="DELETE_ORDER_REQUEST"; 

export const CLEAR_ERRORS = "CLEAR_ERRORS" ;
