export const All_PRODUCT_REQUEST="All_PRODUCT_REQUEST";
export const All_PRODUCT_SUCESS="All_PRODUCT_SUCESS";
export const All_PRODUCT_FAIL="All_PRODUCT_FAIL";

export const Admin_PRODUCT_REQUEST="Admin_PRODUCT_REQUEST";
export const Admin_PRODUCT_SUCESS="Admin_PRODUCT_SUCESS";
export const Admin_PRODUCT_FAIL="Admin_PRODUCT_FAIL";

export const PRODUCT_DETAIL_REQUEST="PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCESS="PRODUCT_DETAIL_SUCESS";
export const PRODUCT_DETAIL_FAIL="PRODUCT_DETAIL_FAIL";

export const REMOVE_PRODUCT_REQUEST = "REMOVE_PRODUCT_REQUEST" ;
export const REMOVE_PRODUCT_SUCESS = "REMOVE_PRODUCT_SUCESS" ;
export const REMOVE_PRODUCT_FAIL = "REMOVE_PRODUCT_FAIL" ;


export const NEW_PRODUCT_REQUEST ="NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCESS ="NEW_PRODUCT_SUCESS";
export const NEW_PRODUCT_RESET ="NEW_PRODUCT_RESET";
export const NEW_PRODUCT_FAIL ="NEW_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST ="DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCESS ="DELETE_PRODUCT_SUCESS";
export const DELETE_PRODUCT_FAIL="DELETE_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST ="UPDATE_PRODUCT_REQUEST"; 
export const UPDATE_PRODUCT_SUCESS ="UPDATE_PRODUCT_SUCESS"; 
export const UPDATE_PRODUCT_FAIL ="UPDATE_PRODUCT_FAIL"; 
export const UPDATE_PRODUCT_RESET ="UPDATE_PRODUCT_RESET"; 

export const SEARCH_PRODUCT_REQUEST ="SEARCH_PRODUCT_REQUEST"; 
export const SEARCH_PRODUCT_SUCESS ="SEARCH_PRODUCT_SUCESS"; 
export const SEARCH_PRODUCT_FAIL ="SEARCH_PRODUCT_FAIL"; 

export const CLEAR_ERRORS = "CLEAR_ERRORS";