export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_FAIL= "LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCESS = "REGISTER_SUCESS";
export const REGISTER_FAIL= "REGISTER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCESS = "LOAD_USER_SUCESS";
export const LOAD_USER_FAIL= "LOAD_USER_FAIL";

export const LOGOUT_SUCESS = "LOGOUT_SUCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_PROFILE_REQUEST="UPUDATE_USER_PROFILE";
export const UPDATE_PROFILE_SUCESS="UPUDATE_USER_SUCESS";
export const UPDATE_PROFILE_RESET="UPUDATE_USER_RESET";
export const UPDATE_PROFILE_FAIL="UPUDATE_USER_FAIL";

export const UPDATE_PASSWORD_REQUEST="UPUDATE_PASSWORD_PROFILE";
export const UPDATE_PASSWORD_SUCESS="UPUDATE_PASSWORD_SUCESS";
export const UPDATE_PASSWORD_RESET="UPUDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL="UPUDATE_PASSWORD_FAIL";

export const ALL_USER_REQUEST = "ALL_USER_REQUEST";
export const ALL_USER_SUCESS = "ALL_USER_SUCESS";
export const ALL_USER_FAIL = "ALL_USER_FAIL";

export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAIL_SUCESS = "USER_DETAIL_SUCESS";
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL";

export const UPDATE_USER_REQUEST ="UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCESS ="UPDATE_USER_SUCESS";
export const UPDATE_USER_RESET ="UPDATE_USER_RESET";
export const UPDATE_USER_FAIL ="UPDATE_USER_FAIL"; 

export const DELETE_USER_REQUEST ="DELETE_USER_REQUEST";
export const DELETE_USER_SUCESS ="DELETE_USER_SUCESS";
export const DELETE_USER_RESET ="DELETE_USER_RESET";
export const DELETE_USER_FAIL ="DELETE_USER_FAIL"; 


export const CLEAR_ERRORS = "CLEAR_ERRORS";
